version: '3.8'

services:
  sentiment-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sentiment-model:latest
    container_name: sentiment-model
    ports:
      - "8002:8002"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
