# -------------------------------------------------------------------------
# docker-compose.yml
# -------------------------------------------------------------------------
version: '3.8'
services:
  company-sentiment:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]